# Chapter 5 ワークフローをDRYにする (Custom actions).
---
name: 'Setup Playwright'
description: 'Setup Playwright with deps and cache'
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: ${{ github.workspace }}

# Custom action は再利用可能なステップです。
# Custom action の種類の一つとして 同じ yaml で記載する Composite action があります。
# Composite action は複数のステップをまとめて再利用可能にすることができます。
# たとえば次のケースが考えられます。
# - 公開されている setup-* がないツールのインストール
# - 認証
# - キャッシュの設定
# - 成果物やテストデータのアップロード
# - 完了通知

runs:
  using: 'composite'
  steps:
    - name: Get Playwright version
      shell: bash
      working-directory: ${{ inputs.working-directory || github.workspace }}
      id: version
      run: |
        PLAYWRIGHT_VERSION=$(jq --raw-output '.devDependencies.playwright' package.json)
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

    - name: Cache Playwright with deps
      uses: actions/cache@v6
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ steps.version.outputs.PLAYWRIGHT_VERSION }}
        restore-keys: playwright-

    - name: Install Playwright with deps
      shell: bash
      working-directory: ${{ inputs.working-directory || github.workspace }}
      run: npx playwright install chromium --with-deps
