name: Chapter 3 - actions/artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ビルド（ダミー）
        run: |
          date > dummy.txt
          mkdir -p output
          zip output/artifact.zip dummy.txt
      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
            name: build
            path: output/
  
  deploy:
    runs-on: ubuntu-latest
    needs: build  # buildジョブ後に実行
    permissions:
      contents: write   # gh release upload に必要
    steps:
      - uses: actions/checkout@v4
      - name: 成果物のダウンロード
        uses: actions/download-artifact@v4
        with:
          name: build
          path: output/
      - name: GitHub Release へのデプロイ
        run: gh release upload v1.0.0 output/artifact.zip --clobber
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
