name: articles/detection

on:
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - "src/**"
  pull_request:
    paths:
      - "articles/detections/**"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      projects: ${{ steps.set-matrix.outputs.projects }}

    steps:
      - uses: actions/checkout@v7
        with:
          # Get the entire history for difference detection
          fetch-depth: 0

      # Automatically obtain changed folders as a JSON array using the plugin!
      - name: Get changed directories
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          json: true
          dir_names: true
          dir_names_max_depth: 3 # articles/detections/xxx
          files: articles/detections/**

      # Finalize the array and pass it to the output
      - name: Set matrix output
        id: set-matrix
        run: |
          # For manual execution (workflow_dispatch), target all projects under atricles/detections/
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            PROJECTS=$(ls -d atricles/detections/*/ | cut -d'/' -f2 | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "projects=$PROJECTS" >> $GITHUB_OUTPUT
          else
            # json array returned from the plugin (e.g. ["atricles/detections/web", "atricles/detections/databases"])
            CHANGED_DIRS='${{ steps.changed-files.outputs.all_changed_files }}'

            if [ "$CHANGED_DIRS" = "[]" ] || [ -z "$CHANGED_DIRS" ]; then
              echo "projects=[]" >> $GITHUB_OUTPUT
            else
              # Trim to "atricles/detections/web" -> "web" instantly with jq
              PROJECTS=$(echo "$CHANGED_DIRS" | jq -c 'map(split("/") | .[2])')
              echo "projects=$PROJECTS" >> $GITHUB_OUTPUT
            fi
          fi

  build:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.projects != '[]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    name: build-and-test (${{ matrix.project }})

    permissions:
      contents: read
    strategy:
      fail-fast: false # Continue other parallel builds even if one project fails
      matrix:
        project: ${{ fromJson(needs.detect-changes.outputs.projects) }}

    steps:
      - uses: actions/checkout@v7
      - name: Log Target Project Info
        run: |
          echo "=========================================================="
          echo "🚀 Processing Project: ${{ matrix.project }}"
          echo "=========================================================="
