name: Chapter 3 - Cache

on:
  # pull_request:
  workflow_dispatch:

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
          # cache: ftrue (default)

  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-node/blob/v4/docs/advanced-usage.md#caching-packages-data
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install --frozen-lockfile

  build-dotnet:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/dotnet
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          cache: true
          cache-dependency-path: '**/packages.lock.json'
      - run: dotnet restore --locked-mode
