# Chapter 4 キャッシュの取り扱い、save, restoreを用いてキャッシュのタイミングを制御する.
--- 
name: Chapter 4 - Cache save,restore

on:
  pull_request:
    paths:
      - ".github/workflows/cache-restore.yaml"
  workflow_dispatch:

jobs:
  build-start:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: |
            ./path-to-cahce
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-

      - run: echo "Do something"

      - name: dummy 
        run: |
          echo "current is: $(date)"
          echo "cache value is: $(cat ./path-to-cahce/file 2>/dev/null)"
          echo "ref: $REF"
          mkdir -p ./path-to-cahce
          date > ./path-to-cahce/file
        env: 
          REF: ${{ github.ref }}

      - uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: |
            ./path-to-cahce
          key: ${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
