# Chapter 3 GitHub Actions での秘密情報の扱い方.
---
name: Chapter 3 (7) - Variables and Secrets

on:
  pull_request:
    paths:
      - '.github/workflows/chapter-3-7-secrets.yaml'
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# GitHub Actions では、リポジトリのシークレットやワークフロー内で定義された変数を扱うことができます。

jobs:
  use_github_token:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
      - name: Show variables.
        env:
          VARIABLES_VALUE: ${{ vars.USER_VALUE }}
          SECRETS_VALUE: ${{ secrets.USER_VALUE }}
        run: |
          echo "$VARIABLES_VALUE"
          echo "$SECRETS_VALUE"

      - name: vars, secrets コンテキストの表示
        # vars コンテキストには、ワークフロー内で定義された変数の情報が格納されています
        # secrets コンテキストには、リポジトリで設定したシークレットの情報が格納されていますが、
        run: |
          echo "${{ toJson(vars) }}"
