# Chapter 3 ジョブとステップの実行制御.
---
name: Chapter 3 (3) - Control Flow

on:
  workflow_dispatch:
    inputs:
      force_error:
        description: '強制的にエラーにしますか？'
        type: boolean
        default: true # デフォルトでエラーにする設定

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# GitHub Actions のジョブは途中で失敗した場合、デフォルトでの挙動でそれ以降のステップはスキップされます。
# また needs でジョブ間の依存関係を設定している場合、後続のジョブはスキップされずにワークフロー全体が終了します。
# しかし、ジョブやステップはより細かく実行制御が可能です。

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: ビルド処理（ダミー）
        id: fail_step
        run: |
          if [ "${{ inputs.force_error }}" = "true" ]; then
            echo "テスト用に強制エラーを起こします..."
            exit 1
          else
            echo "ビルド処理が正常に成功しました！"
          fi

      - name: 失敗時の処理
        # ジョブのステップは if を利用して、前のステップの結果に応じて実行制御が可能です。
        if: ${{ failure() && steps.fail_step.outcome == 'failure' }}
        run: echo "${{ steps.fail_step.outcome }}"

  notify:
    # ジョブの実行制御（if）を利用して、前のジョブの結果に応じて通知を出すことができます。
    runs-on: ubuntu-latest
    needs: build
    # see - https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions
    if: ${{ always() }} # build が失敗でも実行
    permissions:
      contents: read

    steps:
      # - name: Slack通知
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      # $GITHUB_STEP_SUMMARY とは、GitHub Actionsを実行したあとのトップ画面（Summary画面）に、
      # 文字やグラフを自由に書き込めるGitHub専用のファイルパス（環境変数）です

      # 【成功（緑）のときの通知】
      - name: Notify on Success
        if: ${{ needs.build.result == 'success' }}
        run: |
          echo "::notice::【手動テスト】ワークフローが正常に成功しました！"

          { 
            echo "# 🟢 テスト成功通知" 
            echo "手動実行されたジョブが正常に完了しました。"
            echo "- **ステータス:** SUCCESS"
            echo "- [ログを確認する](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          } >> "$GITHUB_STEP_SUMMARY"

      # 【失敗（赤）のときの通知】
      - name: Notify on Failure
        if: ${{ needs.build.result == 'failure' }}
        run: |
          echo "::error::【手動テスト】ワークフローが失敗しました。確認してください！"

          { 
            echo "# ❌ テストエラー通知"
            echo "手動実行されたジョブでエラーを検知しました。"
            echo "- **ステータス:** FAILURE"
            echo "- [ログを確認する](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          } >> "$GITHUB_STEP_SUMMARY"
