# Chapter 4 ユースケース 2. 動的にジョブを構築する.
---
name: Chapter 4 (2) - 2. Dynamically construct jobs

on:
  pull_request:
    paths:
      - '.github/workflows/chapter-4-2-matrix2-dynamic.yaml'
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Matrix strategy はJSONを入力として受け取ることができます。
# たとえば、ジョブ1でJSONを生成し、ジョブ2でそのJSONを利用してMatrix strategyを構築することができます。

jobs:
  job1:
    name: Dynamic job building example
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> "$GITHUB_OUTPUT"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    permissions:
      contents: read
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
