# Chapter 5 メンテナンス性を考慮したワークフロー.
---
name: Chapter 5 (1) - Make the workflow DRY (E2E Tests).

on:
  pull_request:
    paths:
      - '.github/workflows/chapter-5-1-e2e-test.yaml'
      - '.github/workflows/reusables/reusable-e2e-test.yaml'
      - '.github/actions/setup-playwright/action.yaml'
      - 'chapters/e2e/**'
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    uses: ./.github/workflows/reusables/reusable-e2e-test.yaml
    with:
      working-directory: './chapters/e2e'
