# Chapter 3 さまざまなワークフロートリガー
---
name: Chapter 3 (5) - Work flow triggers

on:
  # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
  pull_request:
    # 特定のファイルが変更されたときにトリガーする
    paths:
      - '.github/workflows/chapter-3-5-triggers.yaml'
  push:
    # 特定のブランチに push したときにトリガーする
    branches:
      - 'releases/**'
  # issue を作成したとき、ラベルをつけた時にトリガーする
  issues:
    types: [opened, labeled]
  # `At 16:00 on day-of-month 2.` => 毎月２日のAM 1:00にトリガーする（日本時間）
  # schedule:
  #   - cron: '0 16 2 * *'
  # 手動トリガーとフィルターを設定
  workflow_dispatch:
    inputs:
      deploy_version:
        description: 'デプロイするバージョン'
        required: true
      deploy_target:
        description: 'デプロイ先環境'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# GitHub Actions では、ワークフローのトリガーを柔軟に設定することができます。

jobs:
  build:
    name: Events that trigger workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: イベント
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "github.event: $GITHUB_EVENT_CONTEXT"
