# Chapter 3 ワークフロー内で利用可能な値（コンテキスト）.
---
name: Chapter 3 (1) - Context

on:
  pull_request:
    paths:
      - '.github/workflows/chapter-3-1-context.yaml'
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# ワークフロー内では GitHub Actions に関連するさまざまな情報へアクセスするための値（コンテキスト）が利用できます。

jobs:
  display:
    name: display
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: プルリクエストの情報を表示
        env:
          GITHUB_HEAD_REF: '${{ github.head_ref }}'
        run: |
          echo "プルリクエストのブランチ名: $GITHUB_HEAD_REF"
          echo "プルリクエストの番号: ${{ github.event.pull_request.number }}"
          echo "プルリクエストの作成者": ${{ github.event.pull_request.user.login }}

      - name: github コンテキストの表示
        # github コンテキストには主に、GitHub Actions の実行に関する情報が格納されています
        # Be aware that it contains sensitive information such as github.token!
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "github.action: ${{ github.action }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.env: ${{ github.env }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.workspace: ${{ github.workspace }}"
          echo "github.event: $GITHUB_EVENT_CONTEXT"

      - name: runner コンテキストの表示
        # runner コンテキストには主に、GitHub Actions の実行環境に関する情報が格納されています
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "runner: $RUNNER_CONTEXT"

      - uses: actions/checkout@v7
        # steps コンテキストを利用するには、id を指定する必要があります
        id: checkout

      - name: steps コンテキストの表示
        # steps コンテキストには、同じジョブ内で実行されたステップの情報が格納されています
        run: |
          # actions/checkout のステータスを表示
          echo "steps.checkout.conclusion: ${{ steps.checkout.conclusion }}"

      - name: job コンテキストの表示
        # job コンテキストには、同じジョブ内で実行されたステップの情報が格納されています
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "job.status: ${{ job.status }}"
          echo "job: $JOB_CONTEXT"

      - name: その他のコンテキストの表示
        # - see: https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          NEEDS_CONTEXT: ${{ toJson(needs) }}
          ENV_CONTEXT: ${{ toJson(env) }}
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: |
          echo "matrix: $MATRIX_CONTEXT"
          echo "needs: $NEEDS_CONTEXT"
          echo "env: $ENV_CONTEXT"
          echo "inputs: $INPUTS_CONTEXT"
