# Chapter 3 GitHub Actions での秘密情報の扱い方.
---
name: Chapter 3 (7) - Variables and Secrets

on:
  pull_request:
    paths:
      - '.github/workflows/chapter-3-7-secrets.yaml'
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# GitHub Actions では、リポジトリのシークレットやワークフロー内で定義された変数を扱うことができます。

jobs:
  display:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      # vars と secrets の違いはワークフローのログで '*' でマスクされるかどうかです。
      - name: Show variables.
        env:
          # インジェクション対策として、変数の値を直接 echo するのではなく、
          # 環境変数に格納してから echo するようにしています。
          VARIABLES_VALUE: ${{ vars.USER_VALUE }}
          SECRETS_VALUE: ${{ secrets.USER_VALUE }}
        run: |
          echo "$VARIABLES_VALUE"
          echo "$SECRETS_VALUE"
