# Chapter 4 ジョブによるコンテナの利用.
---
name: Chapter 4 (1) - Use Containers

on:
  pull_request:
    paths:
      - '.github/workflows/chapter-4-1-containers.yaml'
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# アプリケーションをコンテナで開発していたり、ミドルウェアをコンテナで立ち上げたりしている場合
# ジョブにおいてもコンテナを利用することができます。

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # ジョブコンテナを指定することで、ジョブ全体をコンテナ内で実行することができる.
    container:
      image: golang:1.26
    steps:
      - run: go version

  service-container-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # サービスコンテナを指定することで、ジョブ内でサービスコンテナを利用することができる.
    # サービスコンテナはジョブの開始時に起動され、ジョブの終了時に停止されます。
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v7
      - name: Connect postgres
        # ERROR: column d.daticulocale does not exist
        # This occurs when running "psql \l" from a v16 client to a v17 server.
        run: |
          psql --version
          psql -h localhost -U postgres -c 'SELECT version()'
        env:
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}
