name: Chapter 2 - CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトする
        uses: actions/checkout@v4
      - name: Go の環境をセットアップする
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
      - name: フォーマットを実行する
        # フォーマット違反時にステップを失敗させる
        run: test -z $(gofmt -l .)
      - name: 静的解析を実行する
        run: go vet ./...
      - name: テストを実行する
        run: go test
      - name: ビルドを実行する
        run: go build .
