name: Chapter 4 - Containers

on:
  pull_request:
    paths:
      - ".github/workflows/containers.yaml"
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: 
      image: golang:1.23.2
    steps:
      - run: go version
