# Chapter 3 ジョブとステップの実行制御.
---
name: Chapter 3 - Control Flow

on:
  # pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ビルド（失敗)
        id: fail_step
        run: exit 1

      - name: 失敗時の処理
        if: ${{ failure() && steps.fail_step.outcome == 'failure' }}
        run: echo "${{ steps.fail_step.outcome }}"

  notify:
    runs-on: ubuntu-latest
    needs: build
    # see - https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions
    if: ${{ always() }}   # build が失敗でも実行
    steps:
      - name: Slack通知
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
