name: context

on:
  pull_request:
  workflow_dispatch:

jobs:
  display:
    name: display
    runs-on: ubuntu-latest
    steps:
      - name: プルリクエストの情報を表示
        run: |
          echo "プルリクエストのブランチ名: ${{ github.head_ref }}"
          echo "プルリクエストの番号: ${{ github.event.pull_request.number }}"
          echo "プルリクエストの作成者": ${{ github.event.pull_request.user.login }}

      - uses: actions/checkout@v4
        id: checkout
      - name: actions/checkout のステータスを表示
        run: echo "${{ steps.checkout.conclusion }}"
