# Chapter 4 ジョブによるコンテナの利用.
---
name: Chapter 4 - Containers

on:
  pull_request:
    paths:
      - ".github/workflows/containers.yaml"
  workflow_dispatch:

permissions: {}

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container: 
      image: golang:1.23.2
    steps:
      - run: go version

  service-container-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Connect postgres
        # ERROR: column d.daticulocale does not exist
        # This occurs when running "psql \l" from a v16 client to a v17 server.
        run: |
          psql --version
          psql -h localhost -U postgres -c 'SELECT version()'
        env:
          PGPASSWORD: ${{ secrets.PG_PASSWORD }}
