# Chapter 5 再利用可能なメンテナンス性を考慮したワークフロー.
---
name: Chapter 5 - E2E test (Call)

on:
  pull_request:
    paths:
      - ".github/workflows/e2e-test.yaml"
      - ".github/workflows/reusable-e2e-test.yaml"
      - ".github/actions/setup-playwright/action.yaml"
      - "packages/node-e2e/**"
  workflow_dispatch:

permissions: {}

jobs:
  e2e:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-e2e-test.yaml
    with:
      working-directory: "packages/node-e2e"
