# Chapter 1 Hello World、ワークフローの定義ファイルの書き方.
---
name: Chapter 1 - Go Test

on:
  # Events
  # - https://docs.github.com/ja/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#issue_comment
  push:
    branches-ignore:
      - main
      - develop
  issue_comment:
    types: [created, deleted]
  schedule:
    - cron: "0 9 1 * *" # At 09:00 on day-of-month 1.
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
          cache: false

      - name: Build
        run: go build -v .
