# Chapter 4 ユースケース 2. 動的にジョブを構築する.
---
name: Chapter 4 - Matrix strategy use case 2

on:
  pull_request:
    paths:
      - ".github/workflows/matrix-use-case2.yaml"
  workflow_dispatch:

permissions: {}

jobs:
  job1:
    name: Dynamic job building example
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> "$GITHUB_OUTPUT"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    permissions:
      contents: read
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
