# Chapter 4 ユースケース 1. テストの分割.
---
name: Chapter 4 - Matrix strategy use case 1

on:
  pull_request:
    paths:
      - ".github/workflows/matrix-use-case1.yaml"
  workflow_dispatch:

jobs:
  test:
    name: Example of splitting tests and running them in parallel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shared: [1/3, 2/3, 3/3]
    steps:
      - name: Run test
        run: echo "npx jest --shred ${{ matrix.shared }}"
