name: Chapter 3 - Permissions

on:
  pull_request:
    paths:
      - ".github/workflows/permissions.yaml"
  workflow_dispatch:

jobs:
  use_github_token:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show variables.
        env:
          VARIABLES_VALUE: ${{ vars.USER_VALUE }}
          SECRETS_VALUE: ${{ secrets.USER_VALUE }}
        run: | 
          echo "$VARIABLES_VALUE"
          echo "$SECRETS_VALUE"

