# Chapter 5 メンテナンス性を考慮したワークフロー.
---
name: Chapter 5 - E2E test (Call resusable)

on:
  pull_request:
    paths:
      - ".github/workflows/e2e-test.yaml"
      - ".github/workflows/reusable-e2e-test.yaml"
      - ".github/actions/setup-playwrite/action.yaml"
      - "packages/node-e2e/**"
  workflow_dispatch:

jobs:
  e2e:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-e2e-test.yaml
    with:
      working-directory: 'packages/node-e2e'
