name: Chapter 5 - Create test environment & Deploy application.
run-name: "Create test environment & Deploy application: ${{ github.event.pull_request.number }}"

on:
  pull_request:
    types: [ opened, reopened]

jobs:
  create:
    name: Create test environment
    runs-on: ubuntu-latest
    steps:
      - run: echo "Create test environment"

  deploy:
    name: Deploy application
    needs: create
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy application"
