# Chapter 5 プルリクエストが更新されたときに動作確認環境へアプリケーションを再デプロイ.
---
name: Chapter 5 - Update application for test environment
run-name: "Update application for test environment: ${{ github.event.pull_request.number }}"

on:
  pull_request:
    types: [ synchronize ]
  workflow_dispatch:

permissions: {}
defaults:
  run:
    shell: bash

jobs:
  update:
    name: Update application
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - run: echo "Update application"
